<?php
/**
 * SEO Meta Generator Pro — Exporter
 * 
 * Export generated meta tags to HTML, JSON, CSV formats.
 * 
 * @package SEO Meta Generator Pro
 * @version 2.0.0
 */

namespace SEOMetaGen;

class Exporter
{
    /**
     * Export analysis result as downloadable HTML report.
     */
    public function exportHtml(array $result, string $title = 'SEO Meta Report'): string
    {
        $gradeClass = strtolower($result['grade'] ?? 'f');
        $score = $result['overall_score'] ?? 0;
        $url = htmlspecialchars($result['url'] ?? '');
        $pageTitle = htmlspecialchars($result['title'] ?? 'N/A');
        $description = htmlspecialchars($result['description'] ?? 'N/A');
        $keywords = htmlspecialchars($result['keywords'] ?? 'N/A');
        $grade = htmlspecialchars($result['grade'] ?? '-');
        $analyzedAt = htmlspecialchars($result['analyzed_at'] ?? date('Y-m-d H:i:s'));

        $suggestions = '';
        foreach ($result['suggestions'] ?? [] as $s) {
            $suggestions .= '<li>' . htmlspecialchars($s) . "</li>\n";
        }

        $scoresHtml = '';
        foreach ($result['scores'] ?? [] as $key => $val) {
            $color = $val >= 80 ? '#10b981' : ($val >= 50 ? '#f59e0b' : '#ef4444');
            $scoresHtml .= <<<SCORE
            <div class="score-item">
                <span class="score-label">{$key}</span>
                <div class="score-bar">
                    <div class="score-fill" style="width:{$val}%;background:{$color}"></div>
                </div>
                <span class="score-value" style="color:{$color}">{$val}%</span>
            </div>
SCORE;
        }

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{$title}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0f172a;color:#e2e8f0;padding:2rem;line-height:1.6}
.container{max-width:900px;margin:0 auto}
.header{text-align:center;margin-bottom:2rem}
.header h1{font-size:2rem;color:#818cf8;margin-bottom:0.5rem}
.header p{color:#94a3b8}
.score-card{background:linear-gradient(135deg,#1e293b,#334155);border-radius:16px;padding:2rem;margin-bottom:2rem;text-align:center}
.score-circle{width:120px;height:120px;border-radius:50%;margin:0 auto 1rem;display:flex;align-items:center;justify-content:center;font-size:2.5rem;font-weight:700}
.grade-a{background:linear-gradient(135deg,#059669,#10b981);color:#fff}
.grade-b{background:linear-gradient(135deg,#0284c7,#0ea5e9);color:#fff}
.grade-c{background:linear-gradient(135deg,#d97706,#f59e0b);color:#fff}
.grade-d{background:linear-gradient(135deg,#dc2626,#ef4444);color:#fff}
.grade-e{background:linear-gradient(135deg,#991b1b,#b91c1c);color:#fff}
.grade-f{background:linear-gradient(135deg,#450a0a,#7f1d1d);color:#fff}
.scores{display:grid;gap:1rem;max-width:600px;margin:0 auto}
.score-item{display:flex;align-items:center;gap:1rem}
.score-label{width:100px;text-transform:capitalize;font-size:0.9rem;color:#94a3b8;text-align:right}
.score-bar{flex:1;height:8px;background:#334155;border-radius:4px;overflow:hidden}
.score-fill{height:100%;border-radius:4px;transition:width 0.5s}
.score-value{width:50px;font-weight:600;text-align:right}
.meta-details{background:#1e293b;border-radius:12px;padding:1.5rem;margin-bottom:2rem}
.meta-details h2{color:#818cf8;margin-bottom:1rem}
.detail-row{display:flex;gap:1rem;padding:0.75rem 0;border-bottom:1px solid #334155}
.detail-row:last-child{border-bottom:none}
.detail-label{width:120px;color:#94a3b8;font-size:0.9rem;flex-shrink:0}
.detail-value{flex:1;word-break:break-all}
.suggestions{background:#1e293b;border-radius:12px;padding:1.5rem}
.suggestions h2{color:#818cf8;margin-bottom:1rem}
.suggestions li{padding:0.5rem 0;border-bottom:1px solid #334155}
.footer{text-align:center;margin-top:2rem;color:#64748b;font-size:0.85rem}
@media print{body{background:#fff;color:#000}}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>🔍 SEO Meta Report</h1>
        <p>Generated by SEO Meta Generator Pro v2.0</p>
    </div>
    <div class="score-card">
        <div class="score-circle grade-{$gradeClass}">{$grade}</div>
        <div style="font-size:3rem;font-weight:700">{$score}%</div>
        <div style="color:#94a3b8">Overall SEO Score</div>
        <div class="scores" style="margin-top:1.5rem">
            {$scoresHtml}
        </div>
    </div>
    <div class="meta-details">
        <h2>📋 Meta Details</h2>
        <div class="detail-row"><span class="detail-label">URL</span><span class="detail-value">{$url}</span></div>
        <div class="detail-row"><span class="detail-label">Title</span><span class="detail-value">{$pageTitle}</span></div>
        <div class="detail-row"><span class="detail-label">Description</span><span class="detail-value">{$description}</span></div>
        <div class="detail-row"><span class="detail-label">Keywords</span><span class="detail-value">{$keywords}</span></div>
    </div>
    <div class="suggestions">
        <h2>💡 Suggestions</h2>
        <ul>{$suggestions}</ul>
    </div>
    <div class="footer">
        <p>SEO Meta Generator Pro v2.0 | Report generated: {$analyzedAt}</p>
    </div>
</div>
</body>
</html>
HTML;
    }

    /**
     * Export result as JSON.
     */
    public function exportJson(array $result): string
    {
        return json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
    }

    /**
     * Export multiple results as CSV.
     */
    public function exportCsv(array $results): string
    {
        $headers = ['URL', 'Title', 'Description', 'Keywords', 'Score', 'Grade', 'Title Score', 'Desc Score', 'Analyzed At'];
        $lines = [implode(';', $headers)];

        foreach ($results as $r) {
            $row = [
                $this->csvEscape($r['url'] ?? ''),
                $this->csvEscape($r['title'] ?? ''),
                $this->csvEscape($r['description'] ?? ''),
                $this->csvEscape($r['keywords'] ?? ''),
                $r['overall_score'] ?? 0,
                $r['grade'] ?? '-',
                $r['scores']['title'] ?? 0,
                $r['scores']['description'] ?? 0,
                $r['analyzed_at'] ?? '',
            ];
            $lines[] = implode(';', $row);
        }

        return implode("\n", $lines);
    }

    /**
     * Export generated meta tags as HTML snippet.
     */
    public function exportMetaHtml(string $html): string
    {
        return $html;
    }

    /**
     * Send HTTP headers for download.
     */
    public function sendDownload(string $content, string $filename, string $mimeType = 'text/html'): void
    {
        header('Content-Type: ' . $mimeType . '; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($content));
        echo $content;
        exit;
    }

    private function csvEscape(string $value): string
    {
        return '"' . str_replace('"', '""', $value) . '"';
    }
}
